### ISSUE TITLE
Handling refund - Refund button

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#10]
Hello,

You should have your own Refund button as shown here in this example with a different payment gateway: https://gyazo.com/b6b2a33c415b3a44ef1d2166a4ce67b2

Currently there is only 1 button: "Refund manually" which trigger the refund with your gateway but the merchant should have a choice on how to refund the customer (either thru gateway or manually).
That's how it works with all other payment gateways.

Thank you

**Comment by nberhouche** [comment]
Hello t-bo,

Thank you for your insight. This feature is already planned, we'll keep you posted.

Best regards.

**Comment by GIMALima** [comment]
Hello,

You can find our own refund button now available on our latest version.

Best regards.
