### ISSUE TITLE
moyen de paiement non disponible avec produits par abonnement

### ISSUE THREAD

**Issue by philhp** [lyra/plugin-woocommerce#12]
Bonjour,

Voici ma configuration : 
Wordpress : 6.4.3
Woocommerce : 8.5.2
EpayNC for WooCommerce : 1.12

j'utilise le plugin Woo subscriptions, 
dans la fiche produit, mon produit est 'abonnement simple' , je précise biensur le prix et la récurrence 

Dans WooCommerce/Réglages/Paiements
"EpayNC - Paiement standard" est correctement configuré et activé ( il fonctionne très bien avec des produits simple)

"EpayNC - Paiement par abonnement avec WooCommerce Subscriptions" est configuré et activé

mais lorsque je tente d'acheter un produit 'abonnement simple', au moment du checkout j'ai le message suivant : 
Désolé, il semble qu’aucun moyen de paiement ne soit disponible pour les abonnements. Veuillez nous contacter si vous avez besoin d’aide ou si vous désirez mettre en place une alternative.

**Comment by nberhouche** [comment]
Bonjour,
On ne peut pas prononcer sur ce problème car il peut y avoir plusieurs raisons derrière. 
Veuillez contacter le support EpayNC avec les éléments ques vous avez décrits et nous ferons notre possible pour vous fournir une solution au plus vite. 


Cordialement.
