### ISSUE TITLE
individual payment icons

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#13]
You should return individual payment icon files based on the selected payment methods. For example here AMEX icon is not returned, So customer is not aware he can pay with AMEX. It's not the best experience.

![01340d2337f2de3417100ca226105a18](https://github.com/lyra/plugin-woocommerce/assets/2110695/457c3cd5-0bdf-45ca-8907-59c0abdf9fc0)

**Comment by GIMALima** [comment]
Hello,

Thank you for your feedback.

You should use the option "Embedded Smartform extended on merchant site with logos (REST API)" for the field 'Payment data entry mode' to have the logos of all configured payment means displayed for the buyer. The option is available since the version 1.11.0 of our plugin.

Best regards.

**Comment by t-bo** [comment]
AMEX logo is not returned despite having the correct option selected as you can see in screenshot.

**Comment by GIMALima** [comment]
Hello,

The logo on the right of the payment method title is a fixed image [/woo-payzen-payment/assets/images/lyra.png] and you can change it.

As for your case to show the logos of your choosen payment cards, you need to choose the option "**Embedded Smartform extended on merchant site with logos (REST API)**" for the field 'Payment data entry mode' and not "**Embedded payment fields on merchant site (REST API)**" and you will have a result as the following screenshot:

![image](https://github.com/lyra/plugin-woocommerce/assets/33562691/b65b83e3-1d9c-4be9-bdd3-c8e91d006c2a)

**Comment by t-bo** [comment]
![image](https://github.com/lyra/plugin-woocommerce/assets/2110695/13c759ab-a8a7-4431-aa89-7450a22f279d)

Hi, "With logos" is not an option in my case. I'm running latest version.

**Comment by GIMALima** [comment]
Hello,

Can please tell me which white label are you using?

Best regards

**Comment by t-bo** [comment]
Sogecommerce

**Comment by GIMALima** [comment]
The Smartform option is currently not available for SogeCommerce white label so you can not show the logos of your chosen payment cards but you can change the default logo in the path [/woo-payzen-payment/assets/images/lyra.png].

Best regards
