### ISSUE TITLE
Remove duplicate logos when using smartform

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#15]
Please remove the credit cards logo on top when using smartform since this is a duplicate with the other logos below and also innacurate. 
![71142ffe3f9756ef11bd35e7a059189c](https://github.com/user-attachments/assets/c1f1fa9a-dd39-4832-a869-bd8f4e83c3ce)

**Comment by nberhouche** [comment]
Hello t-bo,

In the "Standard payment" settings, you can change "Payment data entry mode" value to "Embedded Smartform extended on merchant site without logos (REST API)", thus will have the following display:

![image](https://github.com/user-attachments/assets/25632cec-1093-4896-ab9a-f56fc31ecff9)


Best regards

**Comment by t-bo** [comment]
That's not what I want to achieve. I want the otherway around. Keep the smartforms logo and remove the top logos.

**Comment by nberhouche** [comment]
For the moment,  you can implement filter "woocommerce_lyrastd_icon" to set the desired logo.
We'll study your request and get to you as soon as possible.

Best regards.
