### ISSUE TITLE
WooCommerce Subscription Integration?

### ISSUE THREAD

**Issue by rahilwazir** [lyra/plugin-woocommerce#2]
Does Epaync or Payzen supports WooCommerce subscription? Seen some part of the code for Payzen which processes PayZen subscription, so I'm curious if it supports recurring subscription with WooCommerce Subscription extension.

**Comment by nabil509** [comment]
Hi @rahilwazir,

Sorry for the delay. This question is typically to report to our support service. We manage here only confirmed bugs on the plugin.

We added support to WooCommerce Subscriptions in recent versions. Please check the CHANGELOG.md at the plugin root directory.
