### ISSUE TITLE
Compatibility with WooCommerce Sequential Order Numbers plugin

### ISSUE THREAD

**Issue by paulokyodai** [lyra/plugin-woocommerce#3]
Good morning, I have installed in Woocommerce, the WooCommerce Sequential Order Numbers plugin, which keeps the order numbers in sequential order. When using the Woo-Paizen-payment form, load the default order ID value from the Wordpress database, so it does not match the order number assigned by the WooCommerce Sequential Order Numbers plugin.
The developer of said plugin indicates the following solution but I don't know which files and where it should be added.
"If you want your payment gateway to be compatible with Sequential Order Numbers, or other plugins that filter the number of orders, you have to make a small change. When you store order data, instead of referencing $ order-> id, refer to to $ order-> get_order_number () "
Thanks

**Comment by nabil509** [comment]
Hi @paulokyodai,

Sorry for the delay. We didn't receive notification for this issue.

I think this can be very risky for the working of the plugin. We use the order ID to identify the order to update, it's not just for display issues.

But, if you want really make this change, you should modify in the `class-wc-gateway-payzen.php` file, inside the `get_order_property()` method. All the accesses to `$order->id` property pass through this function. You can do something like:

`
    public static function get_order_property($order, $property_name)
    {
        if ($property_name === 'id') {
            return $order->get_order_number();
        }

        $method = 'get_' . $property_name;

        if (method_exists($order, $method)) {
            return $order->$method();
        }

        return isset($order->$property_name) ? $order->$property_name : null;
    }
`

Please, this indication is PROVIDED "AS IS", WITHOUT ANY WARRANTY. The modification should be tested on a test environment.
This is a specific development. I close this issue.
