### ISSUE TITLE
Incompatibility with Woocommerce 7.5.1

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#6]
Setup:
WP 6.1.1
PHP 8.1

After upgrading to WC 7.5.1 the following error on checkout page: "Error processing checkout. Please try again." 
This happens with a test credit cart form.

There is no error with 7.4.1 version.

We have checked the logs, no specific errors are returned.

**Comment by nberhouche** [comment]
Hello,

The WC 7.5 version introduced changes in their JS implementation that are causing issues with our integration of credit card form. We are working on a fixt that should be included in the next version of the plugin.

Bestr regards
