### ISSUE TITLE
fatal error apply_filter function doesn't exist

### ISSUE THREAD

**Issue by kalyx** [lyra/plugin-woocommerce#7]
Hi, 

CRITICAL Uncaught Error: Call to undefined function apply_filter() in /var/www/vhosts/aaaa.com/httpdocs/wp-content/plugins/woo-sogecommerce-payment/woo-sogecommerce-payment.php:490

I have find that only in this file ( 8 occurences )

the wp function is apply_filter**s** with the "s" at the end

thx

**Comment by nberhouche** [comment]
Hello @kalyx ,

Thank you for your feedback. We've released version 1.10.6 of the plugin that includes the fix for the issue.

Best regards.
