### ISSUE TITLE
HPOS compatibility

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#8]
As per this article:
https://developer.woocommerce.com/2023/03/07/high-performance-order-storage-is-soon-to-be-the-new-normal/

HPOS will be enabled as Default for new Woocommerce stores starting August 2023.

Can you please make sure your plugin is fully HPOS compatible by then? It is currently indicated not compatible.

**Comment by nberhouche** [comment]
Hello t-bo,

Thank you for bringing this matter to our attention, we'll look into it and get back to you as soon as possible.

Best regards

**Comment by t-bo** [comment]
Hi,
Any update on this? Would be great to have it compatible by now. Thank you

**Comment by nberhouche** [comment]
Hello,

We thank you for your patience. Due to holidays, we didn't have time to look into this subjetc, but we will conduct a study on the impact of the HPOS on our plugin before any schedule eventual development.

Best regards

**Comment by nberhouche** [comment]
Hello there,
The compatibility with HPOS will be included in our next release, due in about 2 weeks time.
Thank again for your patience.

Best regards.

**Comment by nberhouche** [comment]
Hello,

Compatibility with HPOS is included in version 1.12.0 of the plugin which has just been released.
Thank you again for your patience.

Best regards
