### ISSUE TITLE
Support of custom order number

### ISSUE THREAD

**Issue by t-bo** [lyra/plugin-woocommerce#9]
Please consider supporting custom order number. We use the plugin "Sequential Order Numbers for WooCommerce" so it allow us to have custom order number.

Currently you are saving the default order ID in gateway backoffice. In the case of custom order number it can't find the transaction for processing refunds for example. Error:  "Refund error: transaction not found (PSP_010)."

Screenshot: https://gyazo.com/c263e77bd050bd21407c724ad5b31179

**Comment by nberhouche** [comment]
Hello t-bo,
Thank you for contacting us. We'll study this issue and get back to you as soon as possible.

Best regards
